local function read(path)
    local f = io.open(path, "r")
    if not f then
        error("missing file: " .. path, 0)
    end
    local s = f:read("*a")
    f:close()
    return s
end

local load_fn = loadstring or load
local loSrc = read("src/LoadOrder.lua")
local loChunk = load_fn(loSrc)
if not loChunk then
    error("syntax error in src/LoadOrder.lua", 0)
end
local ORDER = loChunk()
if type(ORDER) ~= "table" or #ORDER == 0 then
    error("LoadOrder.lua must return a non-empty table", 0)
end

local parts = {}
parts[#parts + 1] = "-- KailexUI bundle - AUTO-GENERATED by build.lua - do not edit\n"
parts[#parts + 1] = "local Bundle = {}\n"
parts[#parts + 1] = "Bundle.__order = (function()\n" .. loSrc .. "\nend)()\n\n"

for _, name in ipairs(ORDER) do
    local src = read("src/" .. name .. ".lua")
    local transformed, count = src:gsub(
        "^%s*return%s+function%s*%(",
        "Bundle[" .. string.format("%q", name) .. "] = function(",
        1
    )
    if count == 0 then
        error("bad module header in " .. name .. " (first line must be: return function(ctx))", 0)
    end
    parts[#parts + 1] = "-- [[" .. name .. "]]\n" .. transformed .. "\n\n"
end

parts[#parts + 1] = "-- [[init]]\n" .. read("src/init.lua")

local out = table.concat(parts)

local f = io.open("dist/Kailex.lua", "w")
if not f then
    os.execute("mkdir dist")
    f = io.open("dist/Kailex.lua", "w")
end
if not f then
    error("cannot write dist/Kailex.lua", 0)
end
f:write(out)
f:close()
print(("built dist/Kailex.lua (%d bytes, %d modules)"):format(#out, #ORDER))
