return {
    "Core/Services/Env",
    "Core/Primitives/Signal", "Core/Primitives/Maid", "Core/Primitives/Root", "Core/Primitives/Utils",
    "Core/Interaction/Input",
    "Core/Rendering/Tween", "Core/Rendering/Theme", "Core/Rendering/Instance", "Core/Rendering/Icon",
    "Core/Services/Save", "Core/Services/Sound", "Core/Misc/Gui",
    "Core/Interaction/Modal", "Core/Interaction/Drag", "Core/Interaction/Ripple", "Core/Rendering/FX",
    "Core/Overlays/Tooltip", "Core/Overlays/Notify", "Core/Overlays/NotifyCards", "Core/Misc/Callbacks",
    "Core/Overlays/ModalCard",
    "Core/Overlays/Confirm", "Core/Misc/QuickWidgets", "Core/Overlays/ContextMenu",
    "Elements/Base", "Elements/Row",
    "Elements/Label", "Elements/Paragraph", "Elements/Divider", "Elements/Section", "Elements/Button", "Elements/Toggle",
    "Elements/Slider/View", "Elements/Slider/Init", "Elements/Keybind",
    "Elements/Dropdown/View", "Elements/Dropdown/Virtual", "Elements/Dropdown/Actions", "Elements/Dropdown/Init",
    "Elements/TextInput",
    "Elements/ColorPicker/View", "Elements/ColorPicker/Init",
    "Elements/ProgressBar", "Elements/Stepper", "Elements/Segmented", "Elements/Vector3Input", "Elements/DataTable",
    "Window/Class", "Window/Chrome", "Window/Search", "Window/Layout", "Window/State", "Window/Placement",
    "Window/GridRow", "Window/Tab", "Window/TabFilter", "Window/Init",
    "App/MobileButton",
    "App/KeySystem/Logic", "App/KeySystem/View", "App/KeySystem/Init",
    "App/ThemeStore",
    "App/SettingsTab/Sections", "App/SettingsTab/Init",
    "App/Persist", "App/Boot",
}
