return {
    "Core/Services/Env",
    "Core/Primitives/Signal", "Core/Primitives/Maid",
    "Core/Primitives/Root", "Core/Primitives/Utils",
    "Core/Interaction/Input",
    "Core/Rendering/Tween", "Core/Rendering/Theme", "Core/Rendering/Instance",
    "Core/Services/Save", "Core/Services/Sound",
    "Core/Misc/Gui",
    "Core/Interaction/Modal", "Core/Interaction/Drag", "Core/Interaction/Ripple",
    "Core/Rendering/FX",
    "Core/Overlays/Tooltip", "Core/Overlays/Notify", "Core/Misc/Callbacks",
    "Core/Overlays/Confirm", "Core/Misc/QuickWidgets", "Core/Overlays/ContextMenu",
    "Elements/Base",
    "Elements/Label", "Elements/Paragraph", "Elements/Divider",
    "Elements/Section", "Elements/Button", "Elements/Toggle",
    "Elements/Slider", "Elements/Keybind", "Elements/Dropdown",
    "Elements/TextInput", "Elements/ColorPicker", "Elements/ProgressBar",
    "Elements/Stepper", "Elements/Segmented", "Elements/Vector3Input",
    "Elements/DataTable",
    "Window/GridRow", "Window/Tab", "Window/Window",
    "App/MobileButton", "App/KeySystem", "App/ThemeStore",
    "App/SettingsTab", "App/Persist", "App/Boot",
}
